apiVersion: apps/v1
kind: Deployment
metadata:
  name: multibranch-flask-app
  namespace: default
  labels:
    app: multibranch-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multibranch-flask-app
  template:
    metadata:
      labels:
        app: multibranch-flask-app
    spec:
      containers:
        - name: flask-app
          image: modaknarayan/multibranch-flask-app:build-13
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
